#!/usr/bin/env bash

# Get the user to run the command 'whoami'
USER="$1"

# Check if the user has been specified
if [[ -z "$USER" ]]; then
  echo "Usage: $0 <user>"
  exit 1
fi

# Run 'whoami' as the specified user
sudo -u "$USER" whoami
